services:
  - type: web
    name: my-flask-app
    env: python
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app --bind 0.0.0.0:8000
    autoDeploy: true
